<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DrMunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $actual_date = now();
        $dr_municipalities = [
            ['name' => 'Santo Domingo de Guzmán', 'cities_id' => 1, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santiago de los Caballeros', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santo Domingo Este', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santo Domingo Norte', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santo Domingo Oeste', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Cristóbal', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Concepción de la Vega', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Pedro de Macorís', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Romana', 'cities_id' => 16, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Los Alcarrizos', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Francisco de Macorís', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Felipe de Puerto Plata', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Salvaleón de Higüey', 'cities_id' => 15, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Moca', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Juan de la Maguana', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Bonao', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Baní', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Boca Chica', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Azua de Compostela', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Bajos de Haina', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Altagracia', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santa Cruz de Barahona', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cotuí', 'cities_id' => 26, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santa Cruz del Seibo', 'cities_id' => 10, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jarabacoa', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Nagua', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Samana', 'cities_id' => 25, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Tamboril', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Mao', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Victoria (D.M.)', 'cities_id' =>	2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Esperanza', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedro Brand', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sosua', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Hato Mayor del Rey', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Constanza', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Navarrete', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Salcedo', 'cities_id' => 13, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Yaguate', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Mata', 'cities_id' => 26, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Matas de Farfán', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Monte Plata', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Yamasá', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Ignacio de Sabaneta', 'cities_id' => 31, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San José de las Matas', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Antonio de Guerra', 'cities_id' => 2, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San José de Ocoa', 'cities_id' => 28, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Bayaguana', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Carril (D.M.)', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Consuelo', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cambita Garabitos', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Gonzalez', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Gregorio de Nigua', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Licey al Medio', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sánchez', 'cities_id' => 25, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Hato del Yaque (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Fernando de Monte Cristi', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Dajabón', 'cities_id' => 7, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Comendador', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Tapia', 'cities_id' => 13, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Neyba', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Tenares', 'cities_id' => 13, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Grande de Boyá', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Cercado', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Imbert', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Yegua', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Altamira', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Fantino', 'cities_id' => 26, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Río Verde Arriba (D.M.)', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Padre Las Casas', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Víctor (D.M.)', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Miches', 'cities_id' => 10, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San José de Los Llanos', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Gaspar Hernández', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Quisqueya', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Riva', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pimentel', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Montellano', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Luperón', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Maimón', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guaymate', 'cities_id' => 16, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Duvergé', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Peralvillo', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Matas de Santa Cruz', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Canela (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Vicente Noble', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Castillo', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Tireo (D.M.)', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San Rafael del Yuma', 'cities_id' => 15, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cenovi (D.M.)', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Grande de Palenque', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Loma de Cabrera', 'cities_id' => 7, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Río San Juan', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jánico', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Vásquez', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Matanzas', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Laguna Salada', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana de la Mar', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jima Abajo', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Galván', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Veragua (D.M.)', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Factor', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Los Botados (D.M.)', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cabral', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Terrenas', 'cities_id' => 25, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Isabela', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedernales', 'cities_id' => 22, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Castañuela', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Arenoso', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Los Hidalgos', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Paya (D.M.)', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Guaranas', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Uvilla (D.M.)', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Paraíso', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Otra Banda (D.M.)', 'cities_id' => 15, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juan López (D.M.)', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Peña (D.M.)', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Enriquillo', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cabrera', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juan de Herrera', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Tabara Arriba', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Los Almácigos', 'cities_id' => 31, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Iglesia (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Piedra Blanca', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Rincon (D.M.)', 'cities_id' => 17, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Pozo (D.M.)', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Vallejuelo', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'San José de Matanzas (D.M.)', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Nizao', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Monción', 'cities_id' => 31, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Rancho Arriba', 'cities_id' => 28, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Peralta', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Larga', 'cities_id' => 28, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Jaragua', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jimaní', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana del Puerto (D.M.)', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Yayas de Viajama', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pueblo Viejo', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Hondo Valle', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Tamayo', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cevicos', 'cities_id' => 26, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Amina (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Polo', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Maizal (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Matayaya (D.M.)', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Ramon Santana', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pepillo Salcedo', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Palmar (D.M.)', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Rubio (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Bohechío', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Baitoa (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Lagunas de Nisibon', 'cities_id' => 15, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Fundación (D.M.)', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cana Chapetón (D.M.)', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Don Juan (D.M.)', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jaibón de Pueblo Nuevo (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Llano', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jamao al Norte', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Hatillo Palma (D.M.)', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Valle', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Los Ríos', 'cities_id' => 5, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Sonador (D.M.)', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Estebania', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guatapanal (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Ciénaga', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guayabo Dulce (D.M.)', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cristo Rey de Guaraguao (D.M.)', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Partido', 'cities_id' => 7, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Los Cacaos', 'cities_id' => 27, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guayubín', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Banica', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Arroyo Salado (D.M.)', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Mata Palacio (D.M.)', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villarpando (D.M.)', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cayetano Germosen', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Descubierta', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Restauración', 'cities_id' => 7, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Charcas', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedro Corto (D.M.)', 'cities_id' => 29, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Pino', 'cities_id' => 7, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Villa Elisa (D.M.)', 'cities_id' => 20, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Santana (D.M.)', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Entrada (D.M.)', 'cities_id' => 18, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guananico', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juncalito (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Cristóbal', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Eugenio Maria de Hostos', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'José Contreras (D.M.)', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Gonzalo (D.M.)', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jaibón (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Cueva (D.M.)', 'cities_id' => 26, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Blanco (D.M.)', 'cities_id' => 13, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Las Salinas', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jicomé (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Ciénaga (D.M.)', 'cities_id' => 28, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guayabal', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pizarrete (D.M.)', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedro García (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Agua Santa del Yuma (D.M.)', 'cities_id' => 8, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juan Santiago', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Puerto (D.M.)', 'cities_id' => 30, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Palmar Arriba (D.M.)', 'cities_id' => 3, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedro Sánchez (D.M.)', 'cities_id' => 10, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Joba Arriba (D.M.)', 'cities_id' => 11, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pescadería (D.M.)', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Pedro Santana', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Peñón', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Jaquimeyes', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Oviedo', 'cities_id' => 22, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Fundación', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Río Limpio (D.M.)', 'cities_id' => 9, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Postrer Río', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Canoa (D.M.)', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juan Adrián (D.M.)', 'cities_id' => 19, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Juancho (D.M.)', 'cities_id' => 22, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Yerba Buena (D.M.)', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Palmar de Ocoa (D.M.)', 'cities_id' => 4, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Elupina Cordero de las Cañitas (D.M.)', 'cities_id' => 12, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Estero Hondo (D.M.)', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Guayabal (D.M.)', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Majagual (D.M.)', 'cities_id' => 21, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Mella', 'cities_id' => 14, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Sabana Buey (D.M.)', 'cities_id' => 23, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'El Cachón (D.M.)', 'cities_id' => 6, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Boca de Yuma (D.M.)', 'cities_id' => 15, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Caya (D.M.)', 'cities_id' => 32, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'La Isabela (D.M.)', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
            ['name' => 'Maimón (D.M.)', 'cities_id' => 24, 'created_at' => $actual_date, 'updated_at' => $actual_date ],
        ];
        
        DB::table('municipalities')->insert($dr_municipalities);
    }
}
